"""initial_schema

Revision ID: 4c65e1991ced
Revises: 
Create Date: 2026-04-11 05:42:04.406421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c65e1991ced'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_borrowers_id'), 'borrowers', ['id'], unique=False)
    op.create_index(op.f('ix_borrowers_legal_name'), 'borrowers', ['legal_name'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrower_id', sa.Integer(), nullable=False),
    sa.Column('loan_number', sa.String(length=50), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('annual_interest_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('payment_frequency', sa.Enum('monthly', name='paymentfrequency'), nullable=False),
    sa.Column('day_count_convention', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('active', 'closed', name='loanstatus'), nullable=False),
    sa.Column('outstanding_principal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_id'], ['borrowers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.create_index(op.f('ix_loans_loan_number'), 'loans', ['loan_number'], unique=True)
    op.create_table('amortization_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('scheduled_payment', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_portion', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('principal_portion', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amortization_schedule_id'), 'amortization_schedule', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('interest_applied', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('principal_applied', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_amortization_schedule_id'), table_name='amortization_schedule')
    op.drop_table('amortization_schedule')
    op.drop_index(op.f('ix_loans_loan_number'), table_name='loans')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_borrowers_legal_name'), table_name='borrowers')
    op.drop_index(op.f('ix_borrowers_id'), table_name='borrowers')
    op.drop_table('borrowers')
    # ### end Alembic commands ###
